export type Dealer = { id: number; dealer_no: string; company_name: string; contact_name: string; phone: string; province: string; city: string; level: number; status: string };
export type DealerAccount = { id: number; dealer_id: number; username: string; is_active: boolean; created_at: string };
export type Store = { id: number; store_no: string; name: string; contact_name: string; phone: string; dealer_id: number; status: string };
export type Batch = { id: number; batch_no: string; batch_name: string; total_count: number; status: string; prefix: string; activation_status: "inactive" | "partial" | "active"; inactive_count: number; activated_count: number; can_activate: boolean; activation_block_reason?: string | null };
export type Prize = { id: number; name: string; type: "cash" | "upgrade"; cash_amount: string; upgrade_price: string; total_stock: number; issued_stock: number; status: string; per_user_limit: number };
export type Activity = { id: number; name: string; description: string; rules: string; status: string; start_at: string; end_at: string; all_batches: boolean };
export type LotteryCode = { id: number; code_no: string; status: string; created_at: string; drawn_at?: string | null; has_redemption_code?: boolean };
export type CodePage = { items: LotteryCode[]; total: number; page: number; page_size: number };
export type ActivityConfiguration = {
  activity: Activity;
  batch_ids: number[];
  prize_pools: {
    id: number;
    prize_id: number;
    prize_name: string;
    prize_type: string;
    cash_amount: string;
    probability: string;
    daily_limit: number;
    issued_today: number;
    total_stock: number;
    issued_stock: number;
  }[];
  policies: {
    id: number;
    scope: string;
    dealer_id?: number | null;
    province: string;
    city: string;
    district: string;
    version: number;
    status: string;
    note: string;
    prizes: { id: number; prize_id: number; prize_name: string; probability: string; daily_limit: number; issued_today: number }[];
  }[];
};
export type WinnerRecord = {
  id: number;
  consumer_name: string;
  consumer_openid: string;
  client_ip?: string | null;
  client_location?: string | null;
  client_province?: string | null;
  client_city?: string | null;
  client_district?: string | null;
  client_address?: string | null;
  code_no: string;
  batch_no: string;
  distribution_no?: string | null;
  dealer_name: string;
  lottery_policy_scope?: string | null;
  lottery_policy_version?: number | null;
  activity_name: string;
  prize_name: string;
  prize_type: string;
  prize_id?: number | null;
  amount: string;
  cash_order_no?: string | null;
  payment_id?: number | null;
  redemption_status: "pending" | "redeemed" | "expired" | "not_required";
  redeemed_at?: string | null;
  redemption_note?: string | null;
  payment_status?: string | null;
  upgrade_redeem_code?: string | null;
  upgrade_amount?: string | null;
  upgrade_status?: string | null;
  dealer_redemption?: { owner_dealer_name: string; redeeming_dealer_name: string; account_name: string; redeemed_at: string; note: string } | null;
  drawn_at: string;
};
export type WinnerPage = {
  items: WinnerRecord[];
  total: number;
  page: number;
  page_size: number;
};
export type DashboardMetrics = { draw_count: number; winner_count: number; cash_issued: string; pending_redemptions: number };
export type ConsumerSummary = { id: number; openid: string; nickname: string; created_at: string; anonymized_at?: string | null; draw_count: number; win_count: number; last_draw_at?: string | null; risk_status: "normal" | "blocked"; risk_note: string; win_probability_multiplier: string };
export type TrendPoint = { date: string; scan_count: number; draw_count: number; winner_count: number; cash_amount: string };
export type AdminAccount = { id: number; username: string; role: string; is_active: boolean; created_at: string };
export type AuditLog = { id: number; username: string; action: string; target_type: string; target_id?: number; detail: string; created_at: string };
export type Distribution = { id: number; distribution_no: string; batch_id: number; batch_no: string; dealer_id: number; dealer_name: string; start_code_no: string; end_code_no: string; quantity: number; status: string; recorded_at: string };
