from app.api.admin_domains.legacy import router
from app.api.admin_domains.legacy import activate_batch
from app.api.admin_domains.legacy import activate_selected_codes
from app.api.admin_domains.legacy import batch_update_redemption
from app.api.admin_domains.legacy import cancel_replenishment
from app.api.admin_domains.legacy import create_dealer_account
from app.api.admin_domains.legacy import create_distribution
from app.api.admin_domains.legacy import create_replenishment
from app.api.admin_domains.legacy import delete_activity
from app.api.admin_domains.legacy import delete_prize
from app.api.admin_domains.legacy import freeze_dealer
from app.api.admin_domains.legacy import list_batches
from app.api.admin_domains.legacy import list_consumers
from app.api.admin_domains.legacy import list_lottery_records
from app.api.admin_domains.legacy import lookup_redemption_by_draw_number
from app.api.admin_domains.legacy import redeem_coupon
from app.api.admin_domains.legacy import unfreeze_dealer
from app.api.admin_domains.legacy import update_activity_status
from app.api.admin_domains.legacy import update_cash_payment
from app.api.admin_domains.legacy import update_lottery_policy
from app.api.admin_domains.legacy import update_prize_status
from app.api.admin_domains.legacy import update_redemption
from app.api.admin_domains.legacy import update_replenishment
